// <auto-generated />
using System;
using BIerlager2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BIerlager2.Migrations
{
    [DbContext(typeof(BierContext))]
    [Migration("20230219193850_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("BIerlager2.Flasche", b =>
                {
                    b.Property<Guid>("FlascheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GenommenAm")
                        .HasColumnType("TEXT");

                    b.Property<int>("KisteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Raum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Regal")
                        .HasColumnType("INTEGER");

                    b.HasKey("FlascheId");

                    b.ToTable("Flasche");
                });
#pragma warning restore 612, 618
        }
    }
}
